// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownloadTask(arg1) {
  return window['go']['backend']['App']['CancelDownloadTask'](arg1);
}

export function CheckAllEmails() {
  return window['go']['backend']['App']['CheckAllEmails']();
}

export function CheckSingleEmail(arg1) {
  return window['go']['backend']['App']['CheckSingleEmail'](arg1);
}

export function CreateDownloadTask(arg1) {
  return window['go']['backend']['App']['CreateDownloadTask'](arg1);
}

export function CreateEmailAccount(arg1) {
  return window['go']['backend']['App']['CreateEmailAccount'](arg1);
}

export function DeleteEmailAccount(arg1) {
  return window['go']['backend']['App']['DeleteEmailAccount'](arg1);
}

export function GetActiveDownloads() {
  return window['go']['backend']['App']['GetActiveDownloads']();
}

export function GetAppInfo() {
  return window['go']['backend']['App']['GetAppInfo']();
}

export function GetConfig() {
  return window['go']['backend']['App']['GetConfig']();
}

export function GetDownloadTasks(arg1, arg2) {
  return window['go']['backend']['App']['GetDownloadTasks'](arg1, arg2);
}

export function GetDownloadTasksByStatus(arg1) {
  return window['go']['backend']['App']['GetDownloadTasksByStatus'](arg1);
}

export function GetEmailAccounts() {
  return window['go']['backend']['App']['GetEmailAccounts']();
}

export function GetLogs(arg1) {
  return window['go']['backend']['App']['GetLogs'](arg1);
}

export function GetServiceStatus() {
  return window['go']['backend']['App']['GetServiceStatus']();
}

export function GetStatistics(arg1) {
  return window['go']['backend']['App']['GetStatistics'](arg1);
}

export function IsDownloadServiceRunning() {
  return window['go']['backend']['App']['IsDownloadServiceRunning']();
}

export function IsEmailServiceRunning() {
  return window['go']['backend']['App']['IsEmailServiceRunning']();
}

export function MinimizeToTray() {
  return window['go']['backend']['App']['MinimizeToTray']();
}

export function OpenDownloadFolder() {
  return window['go']['backend']['App']['OpenDownloadFolder']();
}

export function OpenFile(arg1) {
  return window['go']['backend']['App']['OpenFile'](arg1);
}

export function PauseDownloadTask(arg1) {
  return window['go']['backend']['App']['PauseDownloadTask'](arg1);
}

export function QuitApp() {
  return window['go']['backend']['App']['QuitApp']();
}

export function RestoreFromTray() {
  return window['go']['backend']['App']['RestoreFromTray']();
}

export function ResumeDownloadTask(arg1) {
  return window['go']['backend']['App']['ResumeDownloadTask'](arg1);
}

export function SelectDownloadFolder() {
  return window['go']['backend']['App']['SelectDownloadFolder']();
}

export function ShowNotification(arg1, arg2) {
  return window['go']['backend']['App']['ShowNotification'](arg1, arg2);
}

export function StartEmailMonitoring() {
  return window['go']['backend']['App']['StartEmailMonitoring']();
}

export function StopEmailMonitoring() {
  return window['go']['backend']['App']['StopEmailMonitoring']();
}

export function TestEmailConnection(arg1) {
  return window['go']['backend']['App']['TestEmailConnection'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['backend']['App']['UpdateConfig'](arg1);
}

export function UpdateEmailAccount(arg1) {
  return window['go']['backend']['App']['UpdateEmailAccount'](arg1);
}
