// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {models} from '../models';

export function CancelDownloadTask(arg1:number):Promise<void>;

export function CheckAllEmails():Promise<Array<backend.EmailCheckResult>>;

export function CheckSingleEmail(arg1:number):Promise<backend.EmailCheckResult>;

export function CreateConfig(arg1:models.AppConfig):Promise<void>;

export function CreateDownloadTask(arg1:models.DownloadTask):Promise<void>;

export function CreateEmailAccount(arg1:models.EmailAccount):Promise<void>;

export function DeleteEmailAccount(arg1:number):Promise<void>;

export function GetActiveDownloads():Promise<Array<models.DownloadTask>>;

export function GetActiveDownloadsCount():Promise<number>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetConfig():Promise<models.AppConfig>;

export function GetDownloadTasks(arg1:number,arg2:number):Promise<backend.GetDownloadTasksResponse>;

export function GetDownloadTasksByStatus(arg1:models.DownloadStatus):Promise<Array<models.DownloadTask>>;

export function GetEmailAccounts():Promise<Array<models.EmailAccount>>;

export function GetEmailMessages(arg1:number,arg2:number):Promise<Array<models.EmailMessage>>;

export function GetServiceStatus():Promise<Record<string, boolean>>;

export function GetStatistics(arg1:number):Promise<Array<models.DownloadStatistics>>;

export function IsEmailServiceRunning():Promise<boolean>;

export function MinimizeToTray():Promise<void>;

export function OpenDownloadFolder():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function PauseDownloadTask(arg1:number):Promise<void>;

export function QuitApp():Promise<void>;

export function RestoreFromTray():Promise<void>;

export function ResumeDownloadTask(arg1:number):Promise<void>;

export function SelectDownloadFolder():Promise<string>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function StartEmailMonitoring():Promise<void>;

export function StopEmailMonitoring():Promise<void>;

export function TestEmailConnection(arg1:models.EmailAccount):Promise<void>;

export function TestEmailConnectionByID(arg1:number):Promise<void>;

export function UpdateConfig(arg1:models.AppConfig):Promise<void>;

export function UpdateEmailAccount(arg1:models.EmailAccount):Promise<void>;
